### ISSUE TITLE
blockcmp 코드 작성

### ISSUE THREAD

**Issue by lllminsuk** [JEONGWOO-C/Project2#26]
blockcmp 함수에 대한 코드 작성 입니다.

**Comment by lllminsuk** [comment]
stat1에는 text1 파일에 대한 정보가 저장되어 있고, stat2 에는 text2 파일에 대한 정보가 저장되어 있습니다.

void blockcmp(){
printf("block compare\n");
if(stat1.st_blocks>stat2.st_blocks)
printf("text1 is bigger\n\n");
else if(stat1.st_blocks<stat2.st_blocks)
printf("text2 is bigger\n\n");
else printf("size are equal\n\n");
}

코드는 위와 같이 작성하였습니다.

**Comment by seyeon326** [comment]
좋네요~

**Comment by jeong9823** [comment]
확인했습니다.

**Comment by Izar111** [comment]
확인했습니다.
