### ISSUE TITLE
blockcmp 코드 리뷰

### ISSUE THREAD

**Issue by lllminsuk** [JEONGWOO-C/Project2#27]
완성된 blockcmp 함수에 대한 리뷰입니다.

**Comment by lllminsuk** [comment]
![image](https://user-images.githubusercontent.com/71426612/167680278-c0dbe9fe-153b-4e5b-bc98-82378ff35969.png)
![image](https://user-images.githubusercontent.com/71426612/167680352-b53cbf65-f74e-4f1b-9eac-175b58497ef8.png)
![image](https://user-images.githubusercontent.com/71426612/167680412-2b74aa8a-cccf-45ff-99d2-d0fd88e3b002.png)
결과 입니다

**Comment by jeong9823** [comment]
확인했습니다.

**Comment by seyeon326** [comment]
확인했습니다 수고하셨어용

**Comment by Izar111** [comment]
확인했습니다. 수고하셨습니다.
